GoodList = t3desk014.mit.edu \
 hibat0016.cmsaf.mit.edu hibat0019.cmsaf.mit.edu \
 t2bat0053.cmsaf.mit.edu t2bat0079.cmsaf.mit.edu t2bat0239.cmsaf.mit.edu t2bat0376.cmsaf.mit.edu t2bat0462.cmsaf.mit.edu t2bat0464.cmsaf.mit.edu t2bat0465.cmsaf.mit.edu t2bat0466.cmsaf.mit.edu t2bat0467.cmsaf.mit.edu t2bat0468.cmsaf.mit.edu t2bat0485.cmsaf.mit.edu t2bat0488.cmsaf.mit.edu t2bat0489.cmsaf.mit.edu t2bat0490.cmsaf.mit.edu t2bat0492.cmsaf.mit.edu t2bat0494.cmsaf.mit.edu t2bat0498.cmsaf.mit.edu t2bat0499.cmsaf.mit.edu t2bat0500.cmsaf.mit.edu

Requirements = (  ( BOSCOCluster == "t3serv008.mit.edu" || ( GLIDEIN_Site == "MIT_CampusFactory" &&  BOSCOCluster == "ce03.cmsaf.mit.edu" && BOSCOGroup == "bosco_cms") ) \
	        && stringListIMember(Machine,"$(GoodList)") == True )
		
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-el7:latest"
