#!/bin/bash
# --------------------------------------------------------------------------------------------------
# monitord     Startup script for the monitor server
#
# chkconfig: - 70 15
# description: Monitor is a process that will go to our log file directory of the production\
#              and monitor the progreess of the cataloging process.
#
# processname: monitord
# config:      /etc/monitord.conf
# pidfile:     /var/run/monitord.pid
# --------------------------------------------------------------------------------------------------
# Source function library.
. /etc/rc.d/init.d/functions

# This will prevent initlog from swallowing up a pass-phrase prompt if
# mod_ssl needs a pass-phrase from the user.
INITLOG_ARGS=""

# Path to the running script, server binary, and short-form for messages.
#monitord=/usr/sbin/monitord
monitord=/usr/local/Kraken/agents/monitord
prog=monitord
pidfile=${PIDFILE-/var/run/monitord.pid}
lockfile=${LOCKFILE-/var/lock/subsys/monitord}

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# Start monitor daemon (monitord)
start() {
    echo -n $"Starting $prog:"
    daemon --user=cmsprod --pidfile=${pidfile} $monitord \&
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}

    # this seems like a hack, but I do not know how to do it differently
    pid=`ps auxw | grep "/bin/bash $monitord" |tr -s ' '|cut -d' ' -f2`
    echo $pid > $pidfile

    return $RETVAL
}

# Stop monitor daemon (monitord)
stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} -d ${STOP_TIMEOUT} $monitord
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile} $monitord
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  condrestart|try-restart)
    if status -p ${pidfile} $monitord >&/dev/null
    then
      stop
      start
    fi
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status|help}"
    RETVAL=2
esac

exit $RETVAL
